Updating Readme
ctron/iot-simulator-example pull request #1
Opened 2020-01-28 14:54 UTC by astoycos

- Add a background section with some extra resources 
- Add ability to use Openshift 4.x GUI
- Update other small parts of ReadMe

2020-01-28 16:11 UTC, ctron requested changes
This looks great. Many thanks for the update. There are only a few nits. I made some suggestions, I hope they work for you.

2020-01-28 16:11 UTC, ctron commented on README.md
> +# Iot Simulator
```suggestion
# IoT Simulator
```

2020-01-28 16:11 UTC, ctron commented on README.md
> +    * Generates arbitrary MQTT or HTPP telemetry messages that are sent to EnMasse's IOT protocol adapter(Eclipse Hono)
```suggestion
    * Generates arbitrary MQTT or HTTP telemetry messages that are sent to EnMasse's IoT protocol adapter (Eclipse Hono)
```

2020-01-28 16:11 UTC, ctron commented on README.md
> +This Demo can be deployed on either a **remote** or **local** openshift instance
```suggestion
This Demo can be deployed on either a **remote** or **local** OpenShift instance 
```

2020-01-28 16:11 UTC, ctron commented on README.md
> +    `oc new-project enmasse-infra`
```suggestion
       oc new-project enmasse-infra
```

2020-01-28 16:11 UTC, ctron commented on README.md
> + `oc apply -f enmasse/install/bundles/enmasse`
```suggestion

    oc apply -f enmasse/install/bundles/enmasse`
```

2020-01-28 16:11 UTC, ctron commented on README.md
> +   `iot-simulator-console-iot-simulator.apps.<your cluster>`
```suggestion
    iot-simulator-console-iot-simulator.apps.<your cluster>
```

2020-01-28 16:58 UTC, astoycos commented
Looks good to me, I resolved all the changes!

2020-01-29 07:27 UTC, ctron approved these changes

2020-01-29 07:27 UTC, merged

2020-01-29 07:27 UTC, ctron commented
Thank you again for the great work!